class_name GDSQLModelSourceGenerator
extends RefCounted
## Builds model scripts from catalog metadata without accessing Controls or files.

const DEFAULT_ROOT := "res://models"
const RESERVED_PROPERTIES: Array[StringName] = [
	&"database_role",
	&"table_name",
	&"primary_key",
	&"access_mode",
	&"relationships",
	&"get_model_context",
	&"is_persisted",
	&"is_relationship_loaded",
	&"get_related",
	&"save",
	&"refresh",
	&"delete",
	&"query",
	&"find",
	&"script",
]


func build(
		table: GDSQLTableDefinition,
		model_class_name: StringName,
		database_role: StringName,
		model_root: String = DEFAULT_ROOT,
) -> GDSQLOperationResult:
	if table == null:
		return _failure(
			&"GDSQL_MODEL_SOURCE_TABLE_REQUIRED",
			"A table definition is required to generate a model binding.",
		)
	var class_name_text := String(model_class_name).strip_edges()
	if not class_name_text.is_valid_identifier():
		return _failure(
			&"GDSQL_MODEL_SOURCE_CLASS_INVALID",
			"Model class '%s' is not a valid GDScript identifier." % class_name_text,
		)
	if database_role == &"":
		return _failure(
			&"GDSQL_MODEL_SOURCE_ROLE_REQUIRED",
			"A logical database role is required.",
		)
	var normalized_root := model_root.strip_edges().trim_suffix("/").simplify_path()
	if not normalized_root.begins_with("res://") \
			or normalized_root.begins_with("res://addons/gdsql"):
		return _failure(
			&"GDSQL_MODEL_SOURCE_ROOT_INVALID",
			"Models must be generated into project-owned files under res://.",
		)
	for column in table.columns:
		var property_name := String(column.name)
		if not property_name.is_valid_identifier():
			return _failure(
				&"GDSQL_MODEL_SOURCE_COLUMN_INVALID",
				"Column '%s' cannot be represented as a GDScript property." % column.name,
			)
		if RESERVED_PROPERTIES.has(column.name):
			return _failure(
				&"GDSQL_MODEL_SOURCE_COLUMN_RESERVED",
				"Column '%s' conflicts with required model metadata." % column.name,
			)

	var result := GDSQLOperationResult.new()
	var generated_class := "%sModelGenerated" % class_name_text
	var file_stem := class_name_text.to_snake_case()
	var generated_path := normalized_root.path_join(
		"generated/%s_model_generated.gd" % file_stem,
	)
	var user_path := normalized_root.path_join("%s.gd" % file_stem)
	var generated_lines: Array[String] = [
		"# Generated by GDSQL from table '%s'. Regenerate this file from the table." \
				% table.name,
		"@abstract",
		"class_name %s" % generated_class,
		"extends %s" % _base_class(database_role),
		"",
	]
	for column in table.columns:
		var type_name := _property_type(column, result)
		var nullable_note := ""
		if column.nullable and column.data_type != TYPE_OBJECT:
			nullable_note = " # %s or null" % column.display_type_name()
		generated_lines.append(
			"var %s: %s%s" % [column.name, type_name, nullable_note],
		)
	generated_lines.append_array(
		[
			"",
			"",
			"func table_name() -> StringName:",
			"\treturn %s" % _string_name_literal(table.name),
			"",
			"",
			"func primary_key() -> StringName:",
			"\treturn %s" % _string_name_literal(table.primary_key),
		],
	)
	if _base_class(database_role) == "GDSQLModel":
		generated_lines.append_array(
			[
				"",
				"",
				"func database_role() -> StringName:",
				"\treturn %s" % _string_name_literal(database_role),
			],
		)
	var user_lines: Array[String] = [
		"class_name %s" % class_name_text,
		"extends \"%s\"" % generated_path,
		"## User-owned model behavior. GDSQL never regenerates this file.",
		"",
		"",
		"static func query() -> GDSQLModelQuery:",
		"\treturn GDSQLModels.query(%s)" % class_name_text,
		"",
		"",
		"static func find(identity: Variant) -> GDSQLQueryResult:",
		"\treturn GDSQLModels.find(%s, identity)" % class_name_text,
	]
	result.value = GDSQLModelSource.new(
		StringName(class_name_text),
		StringName(generated_class),
		generated_path,
		user_path,
		"\n".join(generated_lines) + "\n",
		"\n".join(user_lines) + "\n",
	)
	return result


func _base_class(database_role: StringName) -> String:
	match database_role:
		GDSQLDatabaseRegistry.CONTENT_ROLE:
			return "GDSQLContentModel"
		GDSQLDatabaseRegistry.SAVE_ROLE:
			return "GDSQLSaveModel"
		GDSQLDatabaseRegistry.SETTINGS_ROLE:
			return "GDSQLSettingsModel"
		_:
			return "GDSQLModel"


func _property_type(
		column: GDSQLColumnDefinition,
		result: GDSQLOperationResult,
) -> String:
	if column.data_type != TYPE_OBJECT:
		return (
				"Variant"
				if column.nullable or column.data_type == TYPE_NIL
				else type_string(column.data_type)
		)
	if column.resource_type == null:
		_add_resource_fallback_warning(column, result)
		return "Resource"
	if column.resource_type.resolved_script != null:
		var global_name := column.resource_type.resolved_script.get_global_name()
		if global_name != &"":
			return String(global_name)
		_add_resource_fallback_warning(column, result)
		return "Resource"
	var resource_class := String(column.resource_type.resource_class)
	if resource_class.is_valid_identifier():
		return resource_class
	_add_resource_fallback_warning(column, result)
	return "Resource"


func _add_resource_fallback_warning(
		column: GDSQLColumnDefinition,
		result: GDSQLOperationResult,
) -> void:
	result.add_diagnostic(
		GDSQLQueryDiagnostic.new(
			&"GDSQL_MODEL_SOURCE_RESOURCE_FALLBACK",
			"Column '%s' uses Resource in generated code because its exact script type has no global class name." \
					% column.name,
			GDSQLQueryDiagnostic.Severity.WARNING,
		),
	)


func _string_name_literal(value: StringName) -> String:
	return "&\"%s\"" % String(value).c_escape()


func _failure(code: StringName, message: String) -> GDSQLOperationResult:
	var result := GDSQLOperationResult.new()
	result.add_diagnostic(GDSQLQueryDiagnostic.new(code, message))
	return result
