#!/usr/bin/env bash
set -euo pipefail

REPOSITORY_ROOT="$(git rev-parse --show-toplevel)"
GODOT_EXECUTABLE="${GODOT_BIN:-godot}"
SMOKE_ROOT="$(mktemp -d)"
SMOKE_PROJECT="$SMOKE_ROOT/project"
SMOKE_LOG="$SMOKE_ROOT/godot.log"

cleanup() {
	rm -rf "$SMOKE_ROOT"
}
trap cleanup EXIT

if [ ! -x "$GODOT_EXECUTABLE" ] && ! command -v "$GODOT_EXECUTABLE" >/dev/null 2>&1; then
	echo "Godot executable not found: $GODOT_EXECUTABLE"
	exit 1
fi

mkdir -p "$SMOKE_PROJECT/addons"
cp -R "$REPOSITORY_ROOT/addons/gdsql" "$SMOKE_PROJECT/addons/gdsql"

printf '%s\n' \
	'; Generated by scripts/validate-addon-package.sh' \
	'config_version=5' \
	'' \
	'[application]' \
	'config/name="GDSQL Package Smoke Test"' \
	'config/features=PackedStringArray("4.7")' \
	'' \
	'[editor_plugins]' \
	'enabled=PackedStringArray("res://addons/gdsql/plugin.cfg")' \
	> "$SMOKE_PROJECT/project.godot"

set +e
"$GODOT_EXECUTABLE" --headless --editor --path "$SMOKE_PROJECT" --quit \
	> "$SMOKE_LOG" 2>&1
GODOT_EXIT=$?
set -e

if [ "$GODOT_EXIT" -ne 0 ]; then
	cat "$SMOKE_LOG"
	echo "Packaged addon smoke test exited with code $GODOT_EXIT."
	exit "$GODOT_EXIT"
fi

if grep -Eiq 'SCRIPT ERROR|Parse Error|Failed to load script|Could not resolve (class|script)' "$SMOKE_LOG"; then
	cat "$SMOKE_LOG"
	echo "Packaged addon smoke test found a script loading error."
	exit 1
fi

echo "Packaged addon loaded successfully with $($GODOT_EXECUTABLE --version)."
