name: GDSQL Tests

on:
  push:
    branches: [main, v1.x, develop]
  pull_request:
    branches: [main, v1.x]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        godot-version: [4.7]

    steps:
      - uses: actions/checkout@v4

      - uses: godot-gdunit-labs/gdUnit4-action@v1
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: stable
          version: installed
          publish-report: false
          paths: res://tests
          timeout: 5
